apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-cm
  name: busybox-cm
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: quay.io/quay/busybox:latest
    name: busybox-cm
    envFrom:
      - configMapRef:
          name: my-first-cm
