apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-cm-v2
  name: busybox-cm-v2
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: quay.io/quay/busybox:latest
    name: busybox-cm-v2
    env:
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: my-first-cm
            key: debug_level
      - name: MY_COLOR
        valueFrom:
          configMapKeyRef:
            name: my-first-cm
            key: color
      - name: MY_ENV
        valueFrom:
          configMapKeyRef:
            name: my-first-cm
            key: env



