apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
    - name: init-create-dir
      image: quay.io/cilium/alpine-curl
      command: ['sh', '-c', 'sleep 5 && echo "creating dir" && mkdir -p opt/log && echo "test file on init container" > opt/log/test.txt']
      volumeMounts:
        - name: data
          mountPath: /opt
  containers:
    - image: quay.io/jitesoft/nginx:latest
      name: nginx
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: data
          mountPath: /opt  
  volumes:
    - name: data
      emptyDir: {}      
