apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    env: qa
  name: nginx
spec:
  containers:
  - image: quay.io/jitesoft/nginx:latest
    name: nginx
    ports:
    - containerPort: 8080
  - args:
    - bin/sh
    - -c
    - sleep 3600; echo static pod example
    image: quay.io/quay/busybox:latest
    name: busybox
