apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-first-deploy
  name: my-first-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        env: prod
    spec:
      containers:
      - image: quay.io/jitesoft/nginx:stable
        name: nginx
        resources: {}
status: {}
