apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
    env: qa
  name: nginx
spec:
  containers:
  - image: quay.io/jitesoft/nginx:latest
    name: nginx
    ports:
    - containerPort: 8080
  - image: quay.io/jitesoft/nginx:latest
    name: nginx1


